// Deterministic signature block appended to outbound email bodies — never
// generated by the AI. `bookingLink` is proof that "optional" content handed
// to the model as context gets silently omitted (see the SYSTEM_PROMPT in
// write.ts); a phone number the client explicitly asked for must not be
// subject to that same discretion. See
// docs/superpowers/specs/2026-08-07-client-contact-signature-design.md

const SIGNATURE_CLOSING = 'Best regards,'

export interface ClientSignatureContext {
  companyName: string
  signatureName: string | null
  signatureTitle: string | null
  phone: string | null
  address: string | null
  domain: string | null
}

function presentLines(values: (string | null)[]): string[] {
  return values.filter((value): value is string => value !== null && value.trim().length > 0)
}

// Appends a fixed-format signature after the AI-generated body. Gated
// entirely on `phone`: no phone on file means no signature at all, even if
// address/name/title are set. Closing line is always English, matching the
// "always write in English" instruction write.ts/followup.ts's system
// prompts already enforce regardless of client locale.
export function appendSignatureBlock(body: string, signature: ClientSignatureContext): string {
  if (!signature.phone) return body

  const identityLines = presentLines([signature.signatureName, signature.signatureTitle, signature.companyName])
  const contactLines = presentLines([signature.phone, signature.address, signature.domain])

  const block = [SIGNATURE_CLOSING, identityLines.join('\n'), contactLines.join('\n')].join('\n\n')
  return `${body}\n\n${block}`
}
