// Deterministic signature block appended to outbound email bodies — never
// generated by the AI. `bookingLink` is proof that "optional" content handed
// to the model as context gets silently omitted (see the SYSTEM_PROMPT in
// write.ts); a phone number the client explicitly asked for must not be
// subject to that same discretion. See
// docs/superpowers/specs/2026-08-07-client-contact-signature-design.md

const SIGNATURE_CLOSING = 'Best regards,'

export interface ClientSignatureContext {
  companyName: string
  signatureName: string | null
  signatureTitle: string | null
  phone: string | null
  address: string | null
  domain: string | null
}

// The subset of a client row this module reads. Structural rather than the
// full ClientRow so callers (write.ts, followup.ts) don't need to widen a
// `ClientRow | null` just to satisfy this signature.
export interface SignatureClient {
  name: string
  signature_name: string | null
  signature_title: string | null
  phone: string | null
  address: string | null
  domain: string | null
}

// A campaign's per-field signature overrides — every field null means "no
// override, inherit the client's value". Mirrors campaigns.discover_time /
// discover_timezone's existing null-means-inherit convention.
export interface CampaignSignatureOverrides {
  signatureName: string | null
  signatureTitle: string | null
  phone: string | null
  address: string | null
}

// Resolves the effective signature for one send: each field independently
// prefers the campaign's override, then the client's value, then null. A
// campaign can override just the phone number for a single campaign while
// name/title/address still fall back to the client — same per-field
// resolution as discoverTime/discoverTimezone, not an all-or-nothing switch.
export function resolveSignatureContext(
  client: SignatureClient | null,
  campaignOverrides: CampaignSignatureOverrides,
): ClientSignatureContext {
  return {
    companyName: client?.name ?? '',
    signatureName: campaignOverrides.signatureName ?? client?.signature_name ?? null,
    signatureTitle: campaignOverrides.signatureTitle ?? client?.signature_title ?? null,
    phone: campaignOverrides.phone ?? client?.phone ?? null,
    address: campaignOverrides.address ?? client?.address ?? null,
    domain: client?.domain ?? null,
  }
}

function presentLines(values: (string | null)[]): string[] {
  return values.filter((value): value is string => value !== null && value.trim().length > 0)
}

// Appends a fixed-format signature after the AI-generated body. Gated
// entirely on `phone`: no phone on file means no signature at all, even if
// address/name/title are set. Closing line is always English, matching the
// "always write in English" instruction write.ts/followup.ts's system
// prompts already enforce regardless of client locale.
export function appendSignatureBlock(body: string, signature: ClientSignatureContext): string {
  if (!signature.phone) return body

  const identityLines = presentLines([signature.signatureName, signature.signatureTitle, signature.companyName])
  const contactLines = presentLines([signature.phone, signature.address, signature.domain])

  const block = [SIGNATURE_CLOSING, identityLines.join('\n'), contactLines.join('\n')].join('\n\n')
  return `${body}\n\n${block}`
}
