-- New case-status value for "write was attempted this tick and did not reach
-- a terminal outcome, but will (or may) be retried" — distinct from 'ready'
-- (never attempted) and 'writing' (actively running this instant). Fixes two
-- bugs sharing one root cause (runWriteForCase's unconditional end-of-loop
-- `contacted` write): a gate-blocked first touch silently losing the lead
-- (nothing retried a 'contacted' case with a failed step-0 email), and a
-- human_approve case with only drafts falsely CRM-syncing "First outreach
-- sent" before anyone approved. See
-- docs/superpowers/specs/2026-08-17-outreach-send-waiting-system-design.md.
--
-- ALTER TYPE ... ADD VALUE cannot be used in the same transaction as any
-- statement that *uses* the new value (0011, 0040) — the new value must be
-- committed first. This migration does the ADD VALUE only, in total
-- isolation, exactly like 0040 did for 'writing'; the wait_reason column and
-- its check constraint (which do reference 'waiting' as a literal) are
-- migration 0050, same split as 0040 -> 0041.
alter type case_status add value if not exists 'waiting' after 'writing';
